var App = require('./app');

App.Router.map(function() {

  // generated by ember-generate --scaffold
  this.resource('issues');
  this.resource('issue', {path: '/issues/:issue_id'});
  this.route('edit_issue', {path: '/issues/:issue_id/edit'});
  this.route('new_issue', {path: '/issues/new'});
  // end generated routes

});

